### ISSUE TITLE
Missing targetdir

### ISSUE THREAD

**Issue by vitadisplays** [spaulg/composer-maven-plugin#1]
The target dir is not created after a clean. Also the composer.out could not be created.

**Comment by spaulg** [comment]
composer.out is placed inside the target directory which will be why it could not be created. If the target directory is missing, where is the composer.json file?

I've been using my composer plugin alongside the resources plugin which I use to copy from src to target, creating all the directories and brings the composer.json & composer.lock files with it.

**Comment by vitadisplays** [comment]
Found the problem.
It's a lifecycle problem of a plugin in my pom, that replace/alter the resource plugin.
After alter the lifecycles, all went done.
